/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.assistant.jsonc --include-runtime=false --env-interface=RosterAssistantBindings workers/roster-assistant/bindings.d.ts` (hash: 81bd4b57a216cd95d5e5059f1f0ccea1)
interface __BaseEnv_RosterAssistantBindings {
	LOADER: WorkerLoader;
	OPENAI_API_KEY: string;
	CLASHKING_API_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_RosterAssistantBindings {}
}
interface RosterAssistantBindings extends __BaseEnv_RosterAssistantBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "CLASHKING_API_URL">> {}
}
