/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler/wrangler.assistant.generated.jsonc --include-runtime=false --env-interface=RosterAssistantBindings workers/roster-assistant/bindings.d.ts` (hash: 31ca8f91da98a5822e84cdbfcb36ec12)
interface __BaseEnv_RosterAssistantBindings {
	OPENAI_API_KEY_SECRET: SecretsStoreSecret;
	AI_USAGE_SECRET_SECRET: SecretsStoreSecret;
	LOADER: WorkerLoader;
	CLASHKING_API_ORIGIN: "https://v2-api.clashk.ing";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_RosterAssistantBindings {}
}
interface RosterAssistantBindings extends __BaseEnv_RosterAssistantBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLASHKING_API_ORIGIN">> {}
}
