preserve_hierarchy: true

files:
  - source: /messages/en.json
    dest: /dashboard/en.json
    translation: /messages/%locale%.json
    update_option: update_as_unapproved

commit_message: "chore(l10n): new Crowdin translations"
