map $host $robots_header {
  default "";
  dash.clashk.ing "noindex, nofollow";
}

server {
  listen 3000;
  server_name _;
  root /usr/share/nginx/html;
  add_header X-Robots-Tag $robots_header always;

  location / {
    try_files $uri $uri/ $uri.html /index.html;
  }
}
