import type { Metadata } from "next";
import { ClanSignalLegalShell } from "@/components/landing/explorations/clan-signal/legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy | ClashKing",
  description: "How ClashKing collects, uses, stores, and protects account, game, and app data.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "ClashKing Privacy Policy",
    description: "How ClashKing collects, uses, stores, and protects account, game, and app data.",
    type: "website",
    url: "/privacy",
    images: ["/og/clashking-landing.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: "ClashKing Privacy Policy",
    description: "How ClashKing collects, uses, stores, and protects account, game, and app data.",
    images: ["/og/clashking-landing.png"],
  },
};

export default function PrivacyPolicyPage() {
  return (
    <ClanSignalLegalShell title="Privacy Policy" eyebrow="Effective 17 July 2026">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">1. Introduction</h2>
            <p>
              This policy explains how ClashKing collects, uses, stores, and protects information across the mobile app, web dashboard, Discord bot, admin tooling, and backend services. ClashKing helps players and clans view Clash of Clans statistics, manage server workflows, receive optional notifications, and coordinate rosters, reminders, tickets, and clan activity.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">2. Information We Collect</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">a. Game Data</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Clash of Clans player tags, clan tags, names, statistics, clan information, war history, raid history, leaderboards, and performance metrics retrieved from official game APIs or generated by ClashKing features.</li>
                  <li>Account links between Discord users and Clash of Clans player tags when you or a server administrator use linking, roster, reminder, ticket, role, or dashboard features.</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">b. Authentication Data</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Discord user ID, username/display name, avatar URL, guild membership context, OAuth metadata, and dashboard/admin sessions.</li>
                  <li>Access and refresh tokens needed to keep you signed in. We do not store Discord passwords.</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">c. App Usage Data</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Preferences such as language, theme, selected player tags, dashboard column choices, notification settings, and bookmarked players or clans.</li>
                  <li>Device and app details such as platform, app version, build number, operating system, and optional push notification tokens.</li>
                  <li>Error logs and diagnostics used to fix bugs and protect the service. Sentry scope is limited to the minimum account identifier needed to debug authenticated errors.</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">d. Community and Admin Data</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Discord server configuration, roles, reminders, tickets, strikes, giveaway entries, roster data, announcements, push campaigns, and admin audit events.</li>
                  <li>Security metadata such as IP address, user agent, action, resource, and timestamp for admin audit and abuse-prevention logs.</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">3. How We Use Your Information</h2>
            <p className="mb-4 text-muted-foreground">We use the collected information to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Display your game statistics and clan performance data</li>
              <li>Provide widgets, dashboards, account links, rosters, reminders, tickets, roles, and server management features</li>
              <li>Send optional push notifications and in-app announcements that match your settings or your server administrator&apos;s configuration</li>
              <li>Maintain app functionality and user authentication</li>
              <li>Improve app performance through error tracking and bug fixes</li>
              <li>Ensure compatibility across different devices and operating systems</li>
              <li>Protect users, administrators, and the service from abuse, fraud, unauthorized access, and operational mistakes</li>
              <li>Respond to support, privacy, security, and legal requests</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">4. Data Storage and Security</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">a. Data Storage</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Mobile authentication tokens are stored in secure device storage where available. Dashboard sessions and PKCE state are stored in browser storage.</li>
                  <li>Preferences, selected players, widget support data, cached images, and push settings may be stored locally on your device.</li>
                  <li>Server-side records are stored in ClashKing databases and only kept while needed for the feature, security, audit, or legal obligations.</li>
                  <li>Push tokens are removed when you opt out, log out, delete your account, or when the push provider reports them invalid.</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">b. Security Measures</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Data is encrypted in transit with HTTPS.</li>
                  <li>Secrets are kept server-side and never intentionally exposed through public app or dashboard builds.</li>
                  <li>Admin actions are access-restricted, confirmed for production-sensitive actions, and written to audit logs.</li>
                  <li>We minimize crash-reporting context and avoid selling or sharing personal data for advertising.</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">5. Data Sharing and Disclosure</h2>
            <p className="mb-4 text-muted-foreground">We do not sell your personal data and do not share it for cross-context behavioral advertising. We disclose data only when needed to operate ClashKing, protect the service, comply with law, or process your requests.</p>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">a. Third-Party Services</h3>
                <p className="mb-2 text-muted-foreground">We integrate with the following services:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Discord: OAuth login, bot commands, server features, role workflows, and account linking.</li>
                  <li>Supercell/Clash of Clans API: Game data retrieval and account ownership verification.</li>
                  <li>Firebase/APNs: Optional push notification delivery.</li>
                  <li>Sentry: Error tracking with minimized user context.</li>
                  <li>Bunny/CDN providers: Media hosting for configured assets, ticket transcripts, and generated images where features require it.</li>
                </ul>

              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2 text-primary/80">b. Creator Code Revenue</h3>
                <ul className="list-disc pl-6 space-y-1">
                  <li>When you use our creator code ClashKing, we receive 5% of your in-game purchases from Supercell</li>
                  <li>This revenue sharing is handled entirely by Supercell and does not involve sharing your personal information with us</li>
                  <li>Using our creator code costs you nothing extra</li>
                </ul>
              </div>

            </div>
          </section>
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">6. Your Choices and Rights</h2>
            <p className="mb-4 text-muted-foreground">
              Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or receive a portable copy of your personal data. You may also opt out of optional push notifications in the app or device settings.
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use in-app privacy controls to request an export or deletion where available.</li>
              <li>Log out to clear local session data from the current device.</li>
              <li>Contact ClashKing support for Discord bot, dashboard, roster, ticket, or server-admin data requests that require verification.</li>
              <li>California residents may request disclosure, deletion, correction, and opt-out of sale/share. ClashKing does not sell personal data.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">7. Children</h2>
            <p>
              ClashKing is not directed to children under the minimum age required by local law. We do not knowingly collect children&apos;s personal data. If you believe a child provided personal data to ClashKing, contact us so we can review and delete it where required.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">8. International Transfers</h2>
            <p>
              ClashKing is available globally through supported stores and online services. Your information may be processed in countries other than where you live. When required, we use appropriate safeguards and limit processing to the purposes described in this policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">9. Retention</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Account/session data is kept while your account or session remains active, then deleted or anonymized unless needed for security, audit, or legal obligations.</li>
              <li>Push tokens are deleted immediately on opt-out, logout, account deletion, or invalid-token feedback.</li>
              <li>Admin audit logs are retained for accountability and security for the necessary limitation period.</li>
              <li>Public Clash of Clans history may be retained for leaderboards, analytics, and historical game features, but user-account links are deleted or anonymized when no longer needed.</li>
            </ul>
          </section>
    </ClanSignalLegalShell>
  );
}
